name: Run Behave Tests

on:
  push:
    branches: [ CICD_implementation ]
  pull_request:
    branches: [ CICD_implementation ]

jobs:
  behave-tests:
    runs-on: windows-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install chromedriver-autoinstaller webdriver-manager

      - name: Install WebDriver
        run: |
          if ("${{ matrix.browser }}" -eq "chrome") {
            python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"
          }
          if ("${{ matrix.browser }}" -eq "firefox") {
            python -c "from webdriver_manager.firefox import GeckoDriverManager; GeckoDriverManager().install()"
          }

      - name: Run Behave Tests
        run: |
          behave -f json -o Reports/report_${{ matrix.browser }}.json --define browser=${{ matrix.browser }}