name: Run Behave Tests

on:
  push:
    branches: [CICD_implementation]

jobs:
  behave-tests:
    runs-on: windows-latest  # Run tests on Windows

    strategy:
      matrix:
        browser: [chrome, firefox]
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install chromedriver-autoinstaller webdriver-manager

      - name: Install WebDriver for Chrome or Firefox
        shell: pwsh
        run: |
          if ($env:browser -eq "chrome") {
            python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"
          }
          elseif ($env:browser -eq "firefox") {
            python -c "from webdriver_manager.firefox import GeckoDriverManager; GeckoDriverManager().install()"
          }

      - name: Run Behave Tests
        run: |
          behave -f json -o Reports/report_${{ matrix.browser }}.json --define browser=${{ matrix.browser }}
