name: Run Behave Tests

on:
  push:
    branches: [ CICD_implementation ]  # Change if you're using another branch
  pull_request:
    branches: [ CICD_implementation  ]

jobs:
  behave-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Behave Test
        run:  behave -f json -o Reports/report.json








