name: Run Behave Tests

on:
  push:
    branches: [ CICD_implementation ]
  pull_request:
    branches: [ CICD_implementation ]

jobs:
  behave-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        browser: [chrome, firefox]
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install chromedriver-autoinstaller webdriver-manager behave-html-formatter

      - name: Install WebDriver
        shell: bash
        run: |
          if [ "${{ matrix.browser }}" = "chrome" ]; then
            python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"
          elif [ "${{ matrix.browser }}" = "firefox" ]; then
            python -c "from webdriver_manager.firefox import GeckoDriverManager; GeckoDriverManager().install()"
          fi

      - name: Run Behave Tests
        shell: bash
        run: |
          mkdir -p Reports
          behave -f json -o Reports/report_${{ matrix.os }}_${{ matrix.browser }}.json -f behave_html_formatter:HTMLFormatter -o Reports/report_${{ matrix.os }}_${{ matrix.browser }}.html --define browser=${{ matrix.browser }}

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-${{ matrix.os }}-${{ matrix.browser }}
          path: Reports/
          retention-days: 7